### PR TITLE
added support of optional Byte-Range field in header. (RFC4975 sectio…

### PR DESCRIPTION
**Pull request by mateuszgreczek**
…n 7.3.1)

### CODE REVIEW

**Comment by mateuszgreczek** [comment]
@joantune , @tuijldert can you review this PR, or propose another solution?

**Comment by tuijldert** [comment]
Hi,

Thanks for your contribution, we’re in the process of validating this pull-request.
Can you elaborate on the change within Transaction.cs, what does it solve exactly?


Cheers,
    Tom.

**Comment by mateuszgreczek** [comment]
Hi, thanks for reviewing this. 
I had a problem with parsing MSRP packet which doesn't contain "Byte-Range" header (According to RFC it is optional when packet contains only 1 and whole message). In this case variable 'start' is set to '-1' and it throw Exception in line 738: 'Message.DataContainer.Put(start, data);'.
Maybe there is better solution for this problem, so any suggestions will be helpful.

Regards, Mateusz

PS. Are you able to generate nuget package for this project?

**Comment by tuijldert** [comment]
Fair enough, I've verified the change on the java-version and it's not breaking anything.
Can you change the double equation on size to a simple "<=" in DataContainer.cs in your pull-request?. Than we can merge it in.
Good catch btw.

As you might have guessed, C# is not the main platform supported here, so on Nuget packaging, I suggest another pull request from you on this and we can verify/merge it in if ok.

Hope this helps,
    Tom.

**Comment by tuijldert** [comment]
Done.
Thanks for your contribution.

Cheers,
    Tom.

**Pull request merged**
